---

- hosts: 'node1'
  become: true
  become_user: root

  tasks:

  - name: Creating Server Config
    template:
      src: templates/general.j2
      dest: /etc/my.cnf.d/server.cnf
      owner: root
      group: root
      mode: 0644
